version: '3'
services:
  node:
    env_file: .env
    restart: always
    build: .
    ports:
      - 4500:4500
    volumes:
      - ./:/code
    container_name: node-floats
    extra_hosts:
      - "host.docker.internal:host-gateway"
  mongo:
    image: mongo
    restart: always
    container_name: mongo-floats
  redis:
    image: "redis:alpine"
    restart: always
    container_name: redis-floats
volumes:
  mongodb:
