version: '3'
services:
  node:
    env_file: .env
    restart: always
    build: .
    ports:
      - 4500:4500
    volumes:
      - ./:/code
    container_name: floats
    networks:
      - internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
  mongo:
    image: mongo
    restart: always
    networks:
      - internal
    container_name: mongo
volumes:
  mongodb:

networks:
  internal:
    name: internal
    external: true
